- name: Initial VM setup
  hosts: devops
  become: yes
  tasks:
    -  name: install common packages (including restic)
       apt:
         name: [vim, curl, git, htop, restic]
         update_cache: yes
    -  name: Enable UFW and alllow SSH
       ufw:
         rule: allow
         name: 'OpenSSH'
